name: clippy

on: [push, pull_request]

jobs:
  test:
    name: Linux ${{matrix.toolchain}}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: ["stable", "nightly"]

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v2
      with:
        profile: minimal
        toolchain: ${{ matrix.toolchain }}
        override: true
        components: clippy

    - name: Check clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
